cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/01 ; sbatch start_posterior_stop_01.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/02 ; sbatch start_posterior_stop_02.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/03 ; sbatch start_posterior_stop_03.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/04 ; sbatch start_posterior_stop_04.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/05 ; sbatch start_posterior_stop_05.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/06 ; sbatch start_posterior_stop_06.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/07 ; sbatch start_posterior_stop_07.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/08 ; sbatch start_posterior_stop_08.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/09 ; sbatch start_posterior_stop_09.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/10 ; sbatch start_posterior_stop_10.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/11 ; sbatch start_posterior_stop_11.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/12 ; sbatch start_posterior_stop_12.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/13 ; sbatch start_posterior_stop_13.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/14 ; sbatch start_posterior_stop_14.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/15 ; sbatch start_posterior_stop_15.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/16 ; sbatch start_posterior_stop_16.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/17 ; sbatch start_posterior_stop_17.sh
cd /work/WVDP_EWG_STUDY3/study3py/calibration/sew/MCMC_testing/queso-gp-short/model_000/lowering_history_0.pg24f_ic5etch/18 ; sbatch start_posterior_stop_18.sh
